version: "3.8"
services:
  spaps-mysql:
    container_name: ${APP_NAME}-mysql-${APP_ENV}
    image: 'mysql:8.2.0'
    restart: always
    env_file: 
      - .env
    networks:
      - traefik
    volumes:
      - spaps-mysql-volume:/var/lib/mysql
      - ./deploy:/etc/mysql/mysql.conf.d
      - ./deploy/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 30

  spaps-phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    ports:
      - 51515:80
    env_file: 
      - .env
    depends_on:
      - spaps-mysql
    links: 
      - spaps-mysql
    networks:
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.spaps-phpmyadmin.rule=Host(`${API_PHPMYADMIN_DOMAIN_NAME}`) && PathPrefix(`/`)'
      - 'traefik.http.routers.spaps-phpmyadmin.entrypoints=websecure'
      - 'traefik.http.routers.spaps-phpmyadmin.tls.certresolver=myresolver'
      - 'traefik.http.routers.spaps-phpmyadmin.service=spaps-phpmyadmin'
      - 'traefik.http.services.spaps-phpmyadmin.loadbalancer.server.port=80'
    volumes:
      - spaps-phpmyadmin-volume:/var/lib/phpmyadmin

  api:
    build: '.'
    env_file: 
      - .env
    depends_on:
      spaps-mysql:
        condition: service_healthy
    links: 
      - spaps-mysql
    ports:
      - 51516:3000
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`${API_DOMAIN_NAME}`) && PathPrefix(`/`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls.certresolver=myresolver'
      - 'traefik.http.routers.api.service=api'
      - 'traefik.http.services.api.loadbalancer.server.port=3000'
    networks:
      - traefik

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - spaps-mysql
    links: 
      - spaps-mysql
    networks:
      - traefik
    environment:
      - MYSQL_HOST=spaps-mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 * * * *
      # Make it small
      - GZIP_LEVEL=9
      # As of MySQL 8.0.21 this is needed
      - MYSQLDUMP_OPTS=--no-tablespaces
    restart: unless-stopped

  spaps-redis:
    container_name: ${APP_NAME}-redis-${APP_ENV}
    image: "redis:latest"
    env_file: .env
    ports:
      - "51527:6379"
      - "51528:6380"
    networks:
      - traefik

  spaps-minio:
    container_name: "${APP_NAME}-minio-${APP_ENV}"
    image: minio/minio
    restart: always
    volumes:
      - spaps-minio-data:/minio-data
    command: 'minio server /minio-data --console-address ":9001"'
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-storage.rule=Host(${APP_MINIO_STORAGE_HOST_NAME}) && PathPrefix(/)"
      - "traefik.http.routers.minio-storage.entrypoints=websecure"
      - "traefik.http.routers.minio-storage.tls=true"
      - "traefik.http.routers.minio-storage.tls.certresolver=myresolver"
      - "traefik.http.routers.minio-storage.service=minio-storage-service"
      - "traefik.http.services.minio-storage-service.loadbalancer.server.port=9000"

      - "traefik.http.routers.minio-browser.rule=Host(${APP_MINIO_BROWSER_HOST_NAME}) && PathPrefix(/)"
      - "traefik.http.routers.minio-browser.entrypoints=websecure"
      - "traefik.http.routers.minio-browser.tls=true"
      - "traefik.http.routers.minio-browser.tls.certresolver=myresolver"
      - "traefik.http.routers.minio-browser.service=minio-browser-service"
      - "traefik.http.services.minio-browser-service.loadbalancer.server.port=9001"
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:9001/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - '51525:9000'
      - '51526:9001'
    networks:
      - traefik

  de-fi_connect-minio-createbuckets:
    image: minio/mc
    depends_on:
      - spaps-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://spaps-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb myminio/$AWS_PUBLIC_BUCKET_NAME;
      /usr/bin/mc anonymous set public myminio/$AWS_PUBLIC_BUCKET_NAME;
      exit 0;
      "
    networks:
      - traefik

volumes:
  spaps-api-volume:
  spaps-mysql-volume:
  spaps-phpmyadmin-volume:
  spaps-minio-data:
  
networks:
  traefik:
    external: true
